name = "PiecewiseLinearApprox"
uuid = "fcfa6960-8e2e-11e9-2cde-29dd09221fb3"
authors = ["Richard Dennis <richard.dennis@glasgow.ac.uk>"]
version = "0.1.5"

[compat]
julia = "^1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
